<?xml version="1.0"?>
<!-- Turtlebot Arm gripper URDF-->
<robot xmlns:xacro="http://ros.org/wiki/xacro">
    <xacro:bioloid_F3_fixed parent="arm_wrist_flex_link" name="arm_wrist_F3_0" color="${color}">
      <origin xyz="0 0.016 ${F2_HEIGHT}" rpy="0 ${M_PI} ${-M_PI/2}"/>
    </xacro:bioloid_F3_fixed>
    <!-- gripper joint -->
    <xacro:dynamixel_AX12_fixed parent="arm_wrist_F3_0_link" name="gripper_servo">
      <origin xyz="-0.02275 0 ${-AX12_WIDTH/2}" rpy="${M_PI} ${M_PI/2} 0"/>
    </xacro:dynamixel_AX12_fixed>

    <!-- active finger -->
    <joint name="gripper_joint" type="revolute">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit effort="30" velocity="0.785" lower="-0.40" upper="0.46"/>
      <parent link="gripper_servo_link"/>
      <child link="gripper_active_link"/>
    </joint>
    <link name="gripper_active_link">
      <xacro:box_inertia length="0.025" width="0.0485" height="0.0375" mass="0.010"/>
      <visual>
        <origin xyz=" 0 0 0 " rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://turtlebot_arm_description/meshes/F2.stl" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
        </geometry>
        <material name="${color}"/>
      </visual>
      <collision>
        <origin xyz="0.0 0.0 0.00775" rpy="0 0 0"/>
        <geometry>
          <box size="0.025 0.0485 0.0375"/>
        </geometry>
      </collision>
    </link>
    <xacro:finger_fixed parent="gripper_active_link" name="gripper_active_finger" color="${gripper_color}">
      <origin xyz="0 0 ${F2_HEIGHT}" rpy="0 0 0"/>
    </xacro:finger_fixed>

    <!-- static finger -->
    <!-- As explained here: https://github.com/jenniferBuehler/gazebo-pkgs/wiki/The-Gazebo-grasp-fix-plugin#Important, -->
    <!-- we need to break the static links chain with a fake revolute joint to have an independent gripper_static_link -->
    <!-- This is much more convenient when using the gazebo grasp fix plugin -->
    <joint name="gripper_static_joint" type="revolute">
      <origin xyz="0 0 ${-AX12_HEIGHT-F10_HEIGHT+0.001}" rpy="0 ${M_PI} 0"/>
      <axis xyz="0 1 0"/>
      <limit effort="30" velocity="0.0" lower="0.0" upper="0.0"/>
      <parent link="gripper_servo_link"/>
      <child link="gripper_static_link"/>
    </joint>
    <link name="gripper_static_link">
      <xacro:box_inertia length="0.025" width="0.038" height="0.009" mass="0.005"/>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://turtlebot_arm_description/meshes/F3.stl" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
        </geometry>
        <material name="${color}"/>
      </visual>
      <collision>
        <origin xyz="0.0 0.0 -0.0045" rpy="0 0 0"/>
        <geometry>
          <box size="0.025 0.038 0.009"/>
        </geometry>
      </collision>
    </link>
    <xacro:finger_fixed parent="gripper_static_link" name="gripper_static_finger" color="${gripper_color}">
      <origin xyz="0 0 0" rpy="0 0 ${M_PI}"/>
    </xacro:finger_fixed>
</robot>
